# Generated by Django 5.0.7 on 2024-08-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='nome_mae',
        ),
    ]
