# Generated by Django 5.0.7 on 2024-08-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideranca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='msg',
            field=models.BooleanField(default=False),
        ),
    ]
