# Generated by Django 5.0.7 on 2024-08-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideranca', '0002_contato_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lideranca',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='lideranca',
            name='nome_mae',
        ),
    ]
