# Generated by Django 5.0.7 on 2024-08-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideranca', '0003_remove_lideranca_cpf_remove_lideranca_nome_mae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='local',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='nome_mae',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='secao',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='titulo',
        ),
    ]
