# Generated by Django 5.0.7 on 2024-08-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_statuscontato'),
        ('lideranca', '0004_remove_contato_cpf_remove_contato_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidato.statuscontato'),
        ),
    ]
