# Generated by Django 5.1 on 2024-08-14 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador', '0002_remove_coordenador_cpf_remove_coordenador_nome_mae'),
        ('lideranca', '0005_alter_contato_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lideranca',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coordenador.coordenador'),
        ),
    ]
