# Generated by Django 5.0.7 on 2024-07-30 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderenca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('nome_mae', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=12)),
                ('secao', models.CharField(max_length=10)),
                ('local', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('lideranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liderenca.lideranca')),
            ],
        ),
    ]
