# Generated by Django 5.0.7 on 2024-07-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
            ],
        ),
    ]
