# Generated by Django 5.0.7 on 2024-07-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_do_sistema', models.PositiveIntegerField(verbose_name='Meta do Sistema')),
                ('controle_por_contato', models.PositiveIntegerField(verbose_name='Controle por Contato')),
            ],
        ),
    ]
