# Generated by Django 5.1 on 2024-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_do_contato', models.CharField(max_length=60)),
            ],
        ),
    ]
